include:
  - path: services/postgres.yaml
  - path: services/mongo.yaml
  - path: services/school-erp-backend.yaml
  - path: services/webserver.yaml

services:
  # Extend PowerSync with Mongo and Postgres healthchecks
  powersync:
    extends:
      file: services/powersync.yaml
      service: powersync
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
      pg-db:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - pg-db
    volumes:
      - ./config/pgadmin_servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:

