services:
  nginx:
    container_name: webserver
    build:
      context:
        ../docker/nginx
    ports:
      - "6061:6061"
    depends_on:
      - school-erp-backend
    volumes:
      - ../src:/var/www/html

