services:
  nginx:
    environment:
      - SCHOOL_ERP_BACKEND_PORT=${SCHOOL_ERP_BACKEND_PORT}
    container_name: webserver
    build:
      context:
        ../docker/nginx
    ports:
      - ${SCHOOL_ERP_BACKEND_PORT}:${SCHOOL_ERP_BACKEND_PORT}
    depends_on:
      - school-erp-backend
    volumes:
      - ../src:/var/www/html

