# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.
bucket_definitions:
  global:
    data:
      - SELECT * FROM subjects
      - SELECT * FROM academic_years 
      - SELECT * FROM subject_years # temporary
      - SELECT * FROM assessment_takers # temporary
      - SELECT * FROM sections

  teacher_info:
    parameters:
      - SELECT id as teacher_id FROM teachers WHERE user_id = request.user_id()
    data:
      - SELECT * FROM teachers WHERE id = bucket.teacher_id
      - SELECT * FROM teacher_year WHERE teacher_id = bucket.teacher_id
      - SELECT * FROM teacher_subjects WHERE teacher_id = bucket.teacher_id
      - SELECT * FROM teacher_sections WHERE teacher_id = bucket.teacher_id
      - SELECT * FROM assessments WHERE prepared_by = bucket.teacher_id
